{% set name = "hfradarpy" %}
{% set version = "0.1.5.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/rucool/hfradarpy/archive/{{ version }}.tar.gz
  sha256: a76ae6d4b2b2c09c8cbbc9e07bc94caf88d882fbc4bd5e7797c871dc19997fbc

build:
  entry_points:
    - hfradarpy=hfradarpy.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - xarray
    - netcdf4
    - pyproj
    - click
    - dask-core
    - geopandas
    - cartopy
    - matplotlib-base
    - cmocean
    - joblib

test:
  imports:
    - hfradarpy
  commands:
    - pip check
    - hfradarpy --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/rucool/hfradarpy
  summary: 'Toolbox to read in High Frequency Radar (HFR) files written in the Codar Tabular Format (CTF). Easily read CODAR Ocean Sensors SeaSonde and HELZEL Messtechnik GmbH WERA radial files.'
  license: MIT
  license_file: LICENSE
  doc_url: https://hfradarpy.readthedocs.io/en/latest/
  dev_url: https://github.com/rucool/hfradarpy

extra:
  recipe-maintainers:
    - najascutellatus
    - teresaupdyke
